apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data '{"result":" {{ .data.evaluation.result
          }}","score":"{{ .data.evaluation.score }}","project":"{{ .data.project
          }}","service":"{{ .data.service }}","stage":"{{ .data.stage }}"}'
          https://webhook.site/4d796d31-f4f6-4c13-a2e6-ef5cb58d2db6
      subscriptionID: 0bd37230-b8c2-4574-b287-b5e7ee1b2568
